fragment member on Metaobject {
	id
	member @client {
		avatar
		name
		description
		position
		rating {
			scale_min
			scale_max
			value
		}
	}
	fields {
		reference {
			... on MediaImage {
				image {
					url
				}
			}
		}
		key
		value
	}
}
