fragment product on Product {
	id
	availableForSale
	description
	tags
	title
	totalInventory
	featuredImage {
		altText
		url
	}
	compareAtPriceRange {
		maxVariantPrice {
			amount
			currencyCode
		}
		minVariantPrice {
			amount
			currencyCode
		}
	}
	seo {
		title
		description
	}
}
